name: Tests

on:
    push:
        branches-ignore:
            - 'projects/**'
    pull_request:
        branches-ignore:
            - 'projects/**'

permissions: read-all

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "8.2", "8.3" ]
                laravel: [ "10.0", "11.0" ]
        
        name: PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: xdebug
                env:
                    COMPOSER_TOKEN: ${{ secrets.COMPOSER_TOKEN }}

            -   name: Install dependencies
                run: composer require laravel/framework:^${{ matrix.laravel }}

            -   name: Execute tests
                run: composer test
